on: ["push", "pull_request"]

name: Test Coverage

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v1

    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@v2.3.0
